"""Generate notebooks/MultiHealthQA_end_to_end.ipynb from a list of cells.

Building the notebook from source keeps it diffable and guarantees valid JSON.
Re-run this whenever the narrative changes:  python scripts/build_notebook.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "MultiHealthQA_end_to_end.ipynb"

COLAB_URL = (
    "https://colab.research.google.com/github/"
    "<your-username>/MultiHealthQA/blob/main/notebooks/MultiHealthQA_end_to_end.ipynb"
)


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "execution_count": None,
        "outputs": [],
        "source": text.strip("\n").splitlines(keepends=True),
    }


CELLS = [
    md(f"""# Multilingual Health QA in Low-Resource African Languages — End-to-End

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({COLAB_URL})

This notebook runs the **full pipeline** for the Zindi MSRH challenge using the
`mhqa` package in `src/` (so the notebook and the CLI share one code path):

1. Environment & data
2. EDA — the findings that drive every modelling decision
3. Baselines — retrieval floor and zero-shot mT5
4. Fine-tune mT5 (`configs/mt5_base.yaml`; switch to `mt5_large` on a 16–24 GB GPU)
5. Held-out evaluation (overall + per-language ROUGE)
6. Experiment suite → `reports/experiments.csv`
7. Generate the validated test submission

**Targets to beat:** ROUGE-L `0.6514` · ROUGE-1 `0.7187` · LLM-Judge `0.8522`.

> The platform fills `TargetRLF1`, `TargetR1F1`, `TargetLLM` from the *same*
> generated answer. We optimise whitespace ROUGE (script-safe) locally.
"""),

    md("## 1 — Environment & data"),
    code("""
# On Colab, clone the repo and install deps. Locally, skip the clone.
import os, sys, subprocess
IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    if not os.path.exists("MultiHealthQA"):
        subprocess.run(["git", "clone", "https://github.com/<your-username>/MultiHealthQA.git"], check=True)
    os.chdir("MultiHealthQA")
    subprocess.run(["pip", "install", "-q", "-r", "requirements.txt"], check=True)

# Make the package importable.
sys.path.insert(0, os.path.abspath("src"))
print("cwd:", os.getcwd())
"""),
    code("""
# The 5 competition CSVs must live in ./data (Train/Val/Test/SampleSubmission).
# On Colab, upload them or mount Drive; locally they are already there.
from pathlib import Path
for f in ["Train.csv", "Val.csv", "Test.csv", "SampleSubmission.csv"]:
    p = Path("data") / f
    print(("✅" if p.exists() else "❌"), p)
"""),
    code("""
from mhqa.data import load_all
data = load_all("data")
train, val, test = data["train"], data["val"], data["test"]
print("train", train.shape, "| val", val.shape, "| test", test.shape)
train.head(3)
"""),

    md("""## 2 — Exploratory Data Analysis

The decisive findings (regenerated by `python -m scripts.run_eda`):

* **Canonical templated answers** — only ~61% of answers are unique; the most
  common answer recurs 68×. The task rewards reproducing canonical, in-language
  health responses → high ROUGE is achievable, and **fine-tuned generation** is
  the right tool.
* **Retrieval ceiling ≈ R1 0.44** (per-language char-ngram NN on a CV holdout) —
  below target, so retrieval is a *fallback*, not the model.
* **Mixed scripts** — Amharic = Ge'ez (≈2% Latin), Akan = Latin+diacritics. We
  never lowercase or strip non-ASCII.
* **Answer length** — p90 = 153 words, max 482 → `max_target_length = 512`.
"""),
    code("""
# Regenerate all EDA stats + figures (writes reports/figures/*.png).
import subprocess, sys
subprocess.run([sys.executable, "-m", "scripts.run_eda", "--data-dir", "data", "--out", "reports"], check=True)
"""),
    code("""
from IPython.display import Image, display
for fig in ["01_subset_distribution", "02_length_distributions",
            "03_answer_templating", "04_script_composition"]:
    p = f"reports/figures/{fig}.png"
    print(p)
    display(Image(p))
"""),

    md("## 3 — Baselines"),
    code("""
# Baseline A — retrieval floor (Experiment 1). Fast, CPU-only.
from mhqa.data import stratified_split, ANSWER_COL, LANG_COL
from mhqa.retrieval import PerLanguageRetriever
from mhqa.metrics import compute_rouge, compute_rouge_by_language

trn, holdout = stratified_split(train, val_size=0.05, seed=42)
retr = PerLanguageRetriever().fit(trn)
preds, _, _ = retr.predict(holdout)
print("Retrieval baseline:", compute_rouge(preds, holdout[ANSWER_COL].tolist()))
compute_rouge_by_language(preds, holdout[ANSWER_COL].tolist(), holdout[LANG_COL].tolist()).round(4)
"""),

    md("""## 4 — Fine-tune mT5

`configs/mt5_base.yaml` is the safe default (Colab T4). On a 16–24 GB GPU switch
to `configs/mt5_large.yaml` for the best-score run that targets the leaderboard.
"""),
    code("""
from mhqa.config import load_config
cfg = load_config("configs/mt5_base.yaml")
# For a fast smoke run on weak hardware, uncomment:
# cfg = cfg.with_overrides(model_name="google/mt5-small", num_train_epochs=1)
cfg.model_name, cfg.num_train_epochs, cfg.max_target_length
"""),
    code("""
from mhqa.train import train
trainer, tokenizer = train(cfg)
"""),

    md("## 5 — Held-out evaluation (overall + per-language)"),
    code("""
from mhqa.evaluate import evaluate_model, holdout_for
holdout = holdout_for(cfg)
overall, per_lang, _ = evaluate_model(trainer.model, tokenizer, holdout, cfg, batch_size=8)
print(f"ROUGE-1={overall['rouge1_f1']:.4f}  ROUGE-L={overall['rougeL_f1']:.4f}  "
      f"combined={overall['combined']:.4f}")
per_lang.round(4)
"""),

    md("""## 6 — Experiment suite

Each experiment is a config delta + hypothesis, logged to
`reports/experiments.csv`. Run individually or all at once (long — GPU box).
"""),
    code("""
import subprocess, sys
subprocess.run([sys.executable, "-m", "scripts.run_experiments", "--list"], check=True)
# Example single run:
# subprocess.run([sys.executable, "-m", "scripts.run_experiments",
#                 "--config", "configs/mt5_base.yaml",
#                 "--only", "exp04_mt5base_langprefix"], check=True)
"""),
    code("""
import pandas as pd, os
if os.path.exists("reports/experiments.csv"):
    display(pd.read_csv("reports/experiments.csv"))
"""),

    md("## 7 — Generate the validated test submission"),
    code("""
from mhqa.data import ID_COL, load_split
from mhqa.infer import predict_dataframe
from mhqa.submit import make_submission

retriever = None
if cfg.retrieval_augment or cfg.hybrid_fallback:
    retriever = PerLanguageRetriever().fit(load_split(cfg.train_path, has_answer=True))

test_df = load_split(cfg.test_path, has_answer=False)
test_preds = predict_dataframe(trainer.model, tokenizer, test_df, cfg,
                               retriever=retriever, batch_size=8)
sub = make_submission(
    ids=test_df[ID_COL].tolist(),
    predictions=test_preds,
    output_path=cfg.submission_path,
    sample_submission_path=cfg.sample_submission_path,  # validates shape + IDs
)
print("Wrote", cfg.submission_path)
sub.head()
"""),

    md("""## Next steps to climb the leaderboard

1. Re-run section 4 with `configs/mt5_large.yaml` on the GPU.
2. Sweep `exp06`→`exp11` and record `public_lb` in `reports/experiments.csv`.
3. Update `reports/leaderboard_progression.csv` after each submission and plot it
   for the report's progression chart.
"""),
]


def main() -> None:
    nb = {
        "cells": CELLS,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "colab": {"provenance": []},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote {OUT} ({len(CELLS)} cells)")


if __name__ == "__main__":
    main()
